import { createApp } from 'vue'
// import App from './App.vue'
// import ConditionalApp from './Conditional.vue'
// import ListRendering from './ListRendering.vue'
// import ListConditional from './ListRenderingConditional.vue'
// import MethodApp from './Method.vue'
// import EventHandling from './EventHandling.vue'
// import FormHandling from './FormHandling.vue'
// import BonusDirective from './BonusDirective.vue'
// import ComputedProperty from './ComputedProperty.vue'
// import WatcherApp from './Watcher.vue'
// import App from './AppThree.vue'
// import App from './AppFour.vue'
// import App from './AppFive.vue'
// import App from './AppSix.vue'
// import App from './DynamicComponent.vue'
import App from './TeleportApp.vue'

createApp(App).mount('#app')
